### ISSUE TITLE
howto forward vm pg to localhost

### ISSUE THREAD

**Issue by exfly** [eko/monday#59]
```
<: &postgres
  name: postgres
  type: ssh
  values:
    remote: vagrant@127.0.0.1 # SSH <user>@<hostname>
    args:
      - "-i.vagrant/machines/default/virtualbox/private_key"
      - "-p 2222"
    ports:
     - 5432:5432

projects:
 - name: forward-only
   forward:
    - *postgres

```

I want to do this
`ssh -NT -L 5432:127.0.0.1:5432`

log:
```
❌  An error has occured while trying to write host file for application 'postgres' (ip: 127.0.1.1): open /etc/hosts: permission denied
✅  Successfully mapped hostname 'postgres' with IP '127.0.1.1' and port 9401
🔌  Proxifying postgres locally (127.0.1.1:5432) <-> forwarding to 127.0.0.1:9401
```
